name: "Type Checking [mypy --strict]"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit_tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install test dependencies
        run: pip install .[test]
        shell: bash
      - name: Check package
        run: mypy --strict simple_di
        shell: bash
      - name: Check tests
        run: mypy --strict tests
        shell: bash
