name: "Unit Test"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  unit_tests:
    name: Python ${{ matrix.python-version }}(${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install test dependencies
        run: pip install .[test]
        shell: bash
      - name: Run Unit Tests
        run: pytest tests
        shell: bash
